### ISSUE TITLE
Broken in Rails 2.3.3

### ISSUE THREAD

**Issue by pdeffendol** [pdeffendol/spatial_adapter#5]
spatial_adapter breaks ActiveRecord in Rails 2.3.3 

ArgumentError: wrong number of arguments (2 for 1)
    from vendor/rails/activerecord/lib/active_record/base.rb:2231:in `sanitize_sql_hash_for_conditions'
    from vendor/rails/activerecord/lib/active_record/base.rb:2231:in`sanitize_sql'
    from vendor/rails/activerecord/lib/active_record/base.rb:1494:in `merge_conditions'
    from vendor/rails/activerecord/lib/active_record/base.rb:1492:in`each'
    from vendor/rails/activerecord/lib/active_record/base.rb:1492:in `merge_conditions'
    from vendor/rails/activerecord/lib/active_record/base.rb:1804:in`add_conditions!'
    from vendor/rails/activerecord/lib/active_record/base.rb:1687:in `construct_finder_sql'
    from vendor/rails/activerecord/lib/active_record/base.rb:1548:in`find_every'
    from vendor/rails/activerecord/lib/active_record/base.rb:1505:in `find_initial'
    from vendor/rails/activerecord/lib/active_record/base.rb:613:in`find'
    from (irb):1

**Comment by pdeffendol** [comment]
sanitize_sql_hash_for_conditions takes a second parameter now (table_name) and the overwritten method in spatial_adapter does not.  I spent a bit of time looking into this but unfortunately don't have a quick fix right now.  Overall spatial_adapter is very frustrating when it breaks on new Rails releases, due to it's heavy intrusion into ActiveRecord internals.

**Comment by pdeffendol** [comment]
Thanks sd for the patch to fix 2.3.3 support.  I'm probably going to remove support for Rails < 2.0 so that will clean up the codebase a little.
